services:
  test:
    container_name: test
    image: osml10n:test-ci
    entrypoint:
      - /bin/bash
      - -c
      - |
        cd /app
        nohup ./entrypoint.sh &
        cd tests
        retries=6
        while (( retries > 0 )); do
          ./runtests.lua && exit 0
          (( retries-- ))
          sleep 5
        done
        echo "Error: Giving up!"
        exit 1
    volumes:
      - ./lua_osml10/tests:/app/tests/
