name: Build OCI image

on:
  push:
    branches: ["main", "master"]

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Set timestamp
        shell: bash
        run: |
          timestamp=$(date --utc +%Y-%m-%dT%H_%M_%S%z|tr + -)
          repo=$(echo "ghcr.io/${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "repo=${repo}" >> "$GITHUB_ENV"
          echo "timestamp=${timestamp}" >> "$GITHUB_ENV"
          echo "image_name_tag_version_timestamp=${repo}/osml10n:${{ github.sha }}-${timestamp}" >> "$GITHUB_ENV"

      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build with docker and tag for local use
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          load: true
          tags: |
            osml10n:test-ci

      - name: Test built image
        run: |
          docker compose run test

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          provenance: mode=max
          push: true
          sbom: true
          tags: |
            ${{ env.repo }}/osml10n:latest
            ${{ env.image_name_tag_version_timestamp }}
